select "FACTURA"."idFACTURA", "PASAJERO"."NOMBRE" AS PASAJERO, "FACTURA"."FECHA", "RUTA"."ORIGEN" AS ORIGEN_RUTA, "RUTA"."DESTINO" AS DESTINO_RUTA, "VIAJE"."ORIGEN" AS ORIGEN_VIAJE, "VIAJE"."DESTINO" AS DESTINO_VIAJE, "TICKET"."COSTO" 

from "FACTURA", "RUTA", "VIAJE", "TICKET", "PASAJERO", "RUTA_VIAJE"

WHERE "FACTURA"."idFACTURA" = "TICKET"."FACTURA_idFACTURA" AND "VIAJE"."idVIAJE"= "TICKET"."VIAJE_idVIAJE" AND "RUTA_VIAJE"."VIAJE_idVIAJE" = "VIAJE"."idVIAJE" AND "RUTA_VIAJE"."RUTA_idRUTA" = "RUTA"."idRUTA"


--------------------------------------

INSERT INTO "TIPO_BUS"("NOMBRE", "DESCRIPCION") values('feriado', 'buses de feriado')

INSERT INTO "RUTA"("ORIGEN", "DESTINO") values('progreso', 'alta verapaz')

INSERT INTO "VIAJE"("ORIGEN", "DESTINO","KMS") values('antigua', 'escuintla',15)

INSERT INTO "ASIGNACION_RUTA"("BUS_idBUS","RUTA_idRUTA") values(1,2)