select "FACTURA"."idFACTURA", "PASAJERO"."NOMBRE" AS PASAJERO, "FACTURA"."FECHA", "RUTA"."ORIGEN" AS ORIGEN_RUTA, "RUTA"."DESTINO" AS DESTINO_RUTA, "VIAJE"."ORIGEN" AS ORIGEN_VIAJE, "VIAJE"."DESTINO" AS DESTINO_VIAJE, "TICKET"."COSTO" 

from "FACTURA", "TICKET", "PASAJERO", "RUTA","VIAJE",(select "VIAJE".* , "RUTA".* FROM "VIAJE","RUTA","RUTA_VIAJE" WHERE "RUTA_VIAJE"."RUTA_idRUTA"="RUTA"."idRUTA" AND "RUTA_VIAJE"."VIAJE_idVIAJE"="VIAJE"."idVIAJE")B

WHERE "FACTURA"."idFACTURA" = "TICKET"."FACTURA_idFACTURA" AND B."idVIAJE"= "TICKET"."VIAJE_idVIAJE" AND B."idRUTA"= "RUTA"."ORIGEN" 

