select "FACTURA"."idFACTURA", "PASAJERO"."NOMBRE" AS PASAJERO, "FACTURA"."FECHA", "VIAJE"."ORIGEN" AS ORIGEN_VIAJE, "VIAJE"."DESTINO" AS DESTINO_VIAJE, "TICKET"."COSTO" 

from "FACTURA", "TICKET", "PASAJERO", "VIAJE"

WHERE "PASAJERO"."idPASAJERO" = "FACTURA"."PASAJERO_idPASAJERO"AND "FACTURA"."idFACTURA" = "TICKET"."FACTURA_idFACTURA" and "VIAJE"."idVIAJE"= "TICKET"."VIAJE_idVIAJE" 

